// resources/js/Pages/Auth/Login.vue
<script setup>
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import { Link } from '@inertiajs/vue3'

</script>

<template>
    <div class="flex flex-col items-center justify-center min-h-screen">
        <div class="w-auto border-solid border-2 border-inherit rounded-xl p-4">
            <h1 class="text-5xl text-center mb-8">LOGIN</h1>
            <div class="flex flex-col">
            <InputText class="mb-4 w-96" type="text" v-model="value" placeholder="Email" />
            <InputText class="mb-4" type="password" v-model="value" placeholder="Password"/>
            <Button class="mb-6" label="LOGIN"/>
            <p>Don't have an account? <Link className="text-red-800" href="signup" as="button">Signup</Link> </p>
            </div>
        </div>
    </div>
</template>

// resources/js/Pages/Auth/Login.jsx
import { Head, Link } from "@inertiajs/react";
import React from "react";

const Signup = () => {
    return (
        <>
            <Head title="Login" />
            <div className="min-h-screen">
                <div className="h-screen flex justify-center items-center ">
                    <div className="card bg-white w-96 shadow-xl">
                        <div className="card-body items-center text-center">
                            <form>
                                <h2 className="text-4xl font-bold mb-4 text-center">
                                    Login
                                </h2>
                                <input
                                    type="text"
                                    placeholder="Email"
                                    className="input input-bordered w-full max-w-xs mb-4"
                                />
                                <input
                                    type="password"
                                    placeholder="Password"
                                    className="input input-bordered w-full max-w-xs mb-4"
                                />
                                <div className="card-actions justify-center mb-6">
                                    <button className="btn btn-primary w-full">
                                        Login
                                    </button>
                                </div>

                                <p>
                                    Don't have an account?{" "}
                                    <Link
                                        href="/signup"
                                        className="text-red-800"
                                    >
                                        Sign up
                                    </Link>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Signup;
